#!/bin/bash
while true
do
	curl -s https://api.particle.io/v1/devices/Group12_device1/sum?access_token=9750cacb3c90173295d6b231afe27e49b8aa1bb2 1>P1.txt
	curl -s https://api.particle.io/v1/devices/Group12_device2/sum?access_token=9750cacb3c90173295d6b231afe27e49b8aa1bb2 1>P2.txt
	cp P1.txt ../xbeeChat/
	cp P2.txt ../xbeeChat/
	#curl -s https://api.particle.io/v1/devices/Group12_device1/sum?access_token=9750cacb3c90173295d6b231afe27e49b8aa1bb2>P3.txt
	#curl -s https://api.particle.io/v1/devices/Group12_device1/sum?access_token=9750cacb3c90173295d6b231afe27e49b8aa1bb2>P4.txt
	sleep 1
done